-- DATA ANALYSIS (EDA) - Understand the Dataset
use DataWarehouse;
--Explore all objects in the Database
select * from INFORMATION_SCHEMA.TABLES;

--Explore All Columns in the Database 
select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME= 'dim_customers';

--Dimensions Exploration
--Identifying the unique values (or categories ) in each dimensions.
-- Recognising how data mmight be grouped or segmented, which is useful for later analysis

--Explore All countries our customers come from

select distinct country from gold.dim_customers;

--Explore All categories 'The major Divisions'
select distinct category, subcategory, product_name from gold.dim_product;


-- Date exploration
--Identify the earliest and latest dates (boundaries)

--Find the date of first and last order

select * from gold.fact_sales
where  order_date in ( (select MIN(order_date) from gold.fact_sales), 
					 (select MAX(order_date) from gold.fact_sales) );

select MIN(order_date), MAX(order_date),
		DATEDIFF(month, Min(order_date), max(order_date) ) as order_range_months
		FROM gold.fact_sales;

--Find the Yongest and the oldest customer

select * from gold.dim_customers
where birthdate in ( (select MIN(birthdate) from gold.dim_customers),
					 (select MAX(birthdate) from gold.dim_customers));
select MIN(birthdate) as oldest_birthdate, 
		DATEDIFF(year, min(birthdate), GetDATE()),
		MAX(birthdate) as youngest_birthdate,
		DATEDIFF( year, Max(birthdate), GETDATE())
from gold.dim_customers;


-- Measure Exploration 
select * from gold.fact_sales;
select * from gold.dim_product;
select * from gold.dim_customers;
select SUM(s.sales_amount) as Total_amount, 
	   SUM(s.quantity) as Total_quantity,
	   AVG(s.price) as Avg_price,
	   COUNT( s.order_number) as Total_orders,
	   COUNT( distinct p.product_name) as Total_products,
	   COUNT( distinct c.customer_id) as total_customers
from gold.fact_sales s
join gold.dim_product p
on s.product_key=p.product_key
left join gold.dim_customers c
on c.customer_key= s.customer_key;

select COUNT(distinct c.customer_id) 
from gold.fact_sales s
left join gold.dim_customers c
on c.customer_key=s.customer_key;


--Generate a report that shows all key metrices of the business 

select 'Total sales' AS measure_name , SUM(sales_amount) as measure_value from gold.fact_sales
UNION ALL
select 'Total Qunatity' , SUM(quantity) from gold.fact_sales
UNION ALL
select 'Average Price' , AVG(price) from gold.fact_sales
UNION ALL
select 'Total No. Orders' , COUNT(distinct order_number) from gold.fact_sales
UNION ALL
select 'Total No.Products' , COUNT(product_name) from gold.dim_product
UNION ALL
select 'Total No. Customers' , COUNT(customer_key) from gold.dim_customers


--Find the total customers by countries 
--Find total customers by gender
--Fing total products by category
--What is the avg. cost in each cateogry
--what is the total revenue generated for each cateogry ?
--Find total revenue is generated by each customer 
--what is the distrubution of sold items across countries ?

select * from gold.dim_customers;

select country,COUNT(customer_id) as total_customers
from gold.dim_customers
group by country
order by total_customers desc;

select gender, COUNT(*) as customers
from gold.dim_customers
group by gender
order by COUNT(*) desc;

select * from gold.dim_product;

select * from gold.fact_sales;

select category, COUNT(product_id) as total_products
from gold.dim_product
group by category
order by COUNT(product_id) desc;


select pr.category, AVG(sa.price) as avg_cost
from gold.dim_product pr
left join gold.fact_sales sa
on sa.product_key=pr.product_key
group by pr.category
order by AVG(sa.price) desc;

select pr.category, SUM(sa.sales_amount) as total_amount
from gold.dim_product pr
left join gold.fact_sales sa
on sa.product_key=pr.product_key
group by category
order by total_amount desc;

select pr.category, sa.sales_amount
from gold.dim_product pr
left join gold.fact_sales sa
on sa.product_key=pr.product_key
where category= 'Components';


select * from gold.dim_customers;
select * from gold.dim_product;
select * from gold.fact_sales;

select d.customer_key,
	   d.first_name,
	   d.last_name,
	   SUM(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_customers d
on f.customer_key=d.customer_key
group by d.customer_key, d.first_name,d.last_name
order by total_revenue desc;

select d.country, SUM(f.quantity) as total_quantity
from gold.fact_sales f
left join gold.dim_customers d
on f.customer_key= d.customer_key
group by country
order by total_quantity desc;

-- Rankiing

--Which 5 product generate the highest revenue

 select * from gold.dim_product;
 select * from gold.fact_sales;

 select top 5 d.product_name, SUM(f.sales_amount) as total_revenue
 from gold.fact_sales f
 left join gold.dim_product d
 on d.product_key=f.product_key
 group by d.product_name
 order by total_revenue desc

 --what are the 5 worst performing products in terms of sales

select top 5 d.product_name, SUM(f.sales_amount) as total_revenue
 from gold.fact_sales f
 left join gold.dim_product d
 on d.product_key=f.product_key
 group by d.product_name
 order by total_revenue ;

 --By using window functions
 select * from (
 select ROW_NUMBER() over (order by sum(f.sales_amount) desc) as rank_revenue,
		d.product_name,
		SUM(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_product d
on d.product_key=f.product_key
group by d.product_name ) t 
 where rank_revenue <6;

 --Find the top 10 customers who have generated the highest revenue 

 select top 10 d.customer_key, d.first_name, d.last_name, SUM(f.sales_amount) as total_revenue
 from  gold.fact_sales f
 left join gold.dim_customers d
 on d.customer_key=f.customer_key
 group by d.customer_key, d.first_name, d.last_name
 order by total_revenue desc;

 -- OR 
 select * from (
  select Row_number() over ( order by SUM(f.sales_amount) desc) as rank_customers , d.customer_key, d.first_name, d.last_name, SUM(f.sales_amount) as total_revenue
 from  gold.fact_sales f
 left join gold.dim_customers d
 on d.customer_key=f.customer_key
 group by d.customer_key, d.first_name, d.last_name) t
 where rank_customers <11;



 -- Find 3 customer with the fewest order placed 

  select top 3 d.customer_key, d.first_name, d.last_name, COUNT(distinct order_number) as total_orders
 from  gold.fact_sales f
 left join gold.dim_customers d
 on d.customer_key=f.customer_key
 group by d.customer_key, d.first_name, d.last_name
 order by total_orders ; 

 
